CREATE TABLE `pamirs_schedule_queue` (
  `ID` bigint(20) NOT NULL COMMENT '唯一ID',
  `TASK_TYPE` varchar(50) NOT NULL COMMENT '任务类型',
  `QUEUE_ID` varchar(50) NOT NULL COMMENT '队列',
  `CUR_SERVER` varchar(100) DEFAULT NULL COMMENT '处理服务器',
  `REQ_SERVER` varchar(100) DEFAULT NULL COMMENT '请求服务器',
  `OWN_SIGN` varchar(50) NOT NULL COMMENT '环境',
  `BASE_TASK_TYPE` varchar(50) DEFAULT NULL COMMENT '基础任务类型，2.0版本新增',
  `GMT_CREATE` datetime NOT NULL COMMENT '创建时间',
  `GMT_MODIFIED` datetime NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IND_PAMIRS_SCHEDULE_QUEUEID` (`TASK_TYPE`,`QUEUE_ID`,`OWN_SIGN`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8

CREATE TABLE `pamirs_schedule_server` (
  `ID` bigint(20) NOT NULL,
  `UUID` varchar(100) NOT NULL,
  `TASK_TYPE` varchar(50) NOT NULL,
  `IP` varchar(50) NOT NULL,
  `HOST_NAME` varchar(50) NOT NULL,
  `MANAGER_PORT` bigint(10) NOT NULL,
  `THREAD_NUM` bigint(5) NOT NULL,
  `REGISTER_TIME` datetime NOT NULL,
  `HEARTBEAT_TIME` datetime NOT NULL,
  `VERSION` bigint(12) NOT NULL,
  `JMX_URL` varchar(200) DEFAULT NULL,
  `DEALINFO_DESC` varchar(1000) DEFAULT NULL,
  `NEXT_RUN_START_TIME` varchar(100) DEFAULT NULL,
  `NEXT_RUN_END_TIME` varchar(100) DEFAULT NULL,
  `OWN_SIGN` varchar(50) DEFAULT NULL,
  `BASE_TASK_TYPE` varchar(50) DEFAULT NULL,
  `GMT_CREATE` datetime NOT NULL,
  `GMT_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IND_PAMIRS_SCHEDULE_UUID` (`UUID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8

CREATE TABLE `pamirs_schedule_tasktrun` (
  `ID` bigint(20) NOT NULL,
  `TASK_TYPE` varchar(100) NOT NULL,
  `OWN_SIGN` varchar(50) DEFAULT NULL,
  `BASE_TASK_TYPE` varchar(50) DEFAULT NULL,
  `LAST_ASSIGN_TIME` datetime DEFAULT NULL,
  `LAST_ASSIGN_UUID` varchar(100) DEFAULT NULL,
  `GMT_CREATE` datetime NOT NULL,
  `GMT_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IND_PAMIRS_SCHEDULE_RUN_TASK` (`TASK_TYPE`,`OWN_SIGN`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8

CREATE TABLE `pamirs_schedule_tasktype` (
  `ID` bigint(20) NOT NULL,
  `TASK_TYPE` varchar(100) NOT NULL,
  `LAST_ASSIGN_TIME` datetime DEFAULT NULL,
  `LAST_ASSIGN_UUID` varchar(100) DEFAULT NULL,
  `HEARTBEAT_RATE` bigint(10) DEFAULT NULL COMMENT '心跳频率',
  `JUDGE_DEAD_INTERVAL` bigint(10) DEFAULT NULL COMMENT '判断死亡间隔',
  `THREAD_NUMBER` bigint(5) DEFAULT NULL COMMENT '路线数量',
  `EXECUTE_NUMBER` int(11) DEFAULT NULL COMMENT '执行数量',
  `FETCH_NUMBER` int(11) DEFAULT NULL COMMENT '抓取数量',
  `SLEEP_TIME_NODATA` float(10,3) DEFAULT NULL COMMENT '无数据休眠时间',
  `SLEEP_TIME_INTERVAL` float(10,3) DEFAULT NULL COMMENT '休眠间隔',
  `PROCESSOR_TYPE` varchar(20) DEFAULT NULL COMMENT '处理类别',
  `PERMIT_RUN_START_TIME` varchar(100) DEFAULT NULL COMMENT '允许执行开始时间',
  `PERMIT_RUN_END_TIME` varchar(100) DEFAULT NULL COMMENT '允许执行结束时间',
  `DEAL_BEAN_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT '执行bean名称',
  `EXPIRE_OWN_SIGN_INTERVAL` float(10,2) DEFAULT NULL COMMENT '到期持有签名间隔',
  `GMT_CREATE` datetime NOT NULL,
  `GMT_MODIFIED` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `IND_PAMIRS_TASKTYPE_TASKTYPE` (`TASK_TYPE`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8